<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="9" passed="2" failed="7" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-05-11T20:01:16 AST" name="IcNetbanking" finished-at="2023-05-11T20:02:43 AST" duration-ms="86271">
    <groups>
    </groups>
    <test started-at="2023-05-11T20:01:16 AST" name="BankingApp Test" finished-at="2023-05-11T20:02:43 AST" duration-ms="86271">
      <class name="com.icnetbanking.testcases.TC_Register_003_Test">
        <test-method is-config="true" signature="setup(java.lang.reflect.Method)[pri:0, instance:com.icnetbanking.testcases.TC_Register_003_Test@57a3af25]" started-at="2023-05-11T20:02:19 AST" name="setup" finished-at="2023-05-11T20:02:21 AST" duration-ms="2897" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.icnetbanking.testcases.TC_Register_003_Test.RegisterNewAccount(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="RegisterNewAccount(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:1, instance:com.icnetbanking.testcases.TC_Register_003_Test@57a3af25]" started-at="2023-05-11T20:02:21 AST" name="RegisterNewAccount" data-provider="gettestdatafromexcel" finished-at="2023-05-11T20:02:26 AST" duration-ms="4665" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[mayuri]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[kamal]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[mayuri2010@gmail.com]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[4545454]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[test@123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertTrue(Assert.java:52)
at com.icnetbanking.testcases.TC_Register_003_Test.RegisterNewAccount(TC_Register_003_Test.java:57)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- RegisterNewAccount -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.icnetbanking.testcases.TC_Register_003_Test@57a3af25]" started-at="2023-05-11T20:02:26 AST" name="teardown" finished-at="2023-05-11T20:02:26 AST" duration-ms="256" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="setup(java.lang.reflect.Method)[pri:0, instance:com.icnetbanking.testcases.TC_Register_003_Test@57a3af25]" started-at="2023-05-11T20:02:26 AST" name="setup" finished-at="2023-05-11T20:02:29 AST" duration-ms="2560" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.icnetbanking.testcases.TC_Register_003_Test.RegisterNewAccount(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="RegisterNewAccount(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:1, instance:com.icnetbanking.testcases.TC_Register_003_Test@57a3af25]" started-at="2023-05-11T20:02:29 AST" name="RegisterNewAccount" data-provider="gettestdatafromexcel" finished-at="2023-05-11T20:02:34 AST" duration-ms="5077" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[jamuna]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[soundar]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[jamuna1234@gmail.com]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[5454454]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[test@124]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertTrue(Assert.java:52)
at com.icnetbanking.testcases.TC_Register_003_Test.RegisterNewAccount(TC_Register_003_Test.java:57)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- RegisterNewAccount -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.icnetbanking.testcases.TC_Register_003_Test@57a3af25]" started-at="2023-05-11T20:02:34 AST" name="teardown" finished-at="2023-05-11T20:02:35 AST" duration-ms="313" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="setup(java.lang.reflect.Method)[pri:0, instance:com.icnetbanking.testcases.TC_Register_003_Test@57a3af25]" started-at="2023-05-11T20:02:35 AST" name="setup" finished-at="2023-05-11T20:02:38 AST" duration-ms="2793" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.icnetbanking.testcases.TC_Register_003_Test.RegisterNewAccount(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="RegisterNewAccount(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:1, instance:com.icnetbanking.testcases.TC_Register_003_Test@57a3af25]" started-at="2023-05-11T20:02:38 AST" name="RegisterNewAccount" data-provider="gettestdatafromexcel" finished-at="2023-05-11T20:02:42 AST" duration-ms="4581" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[nandhini]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[bala]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[nandhini7890@gmail.com]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[4545435]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[test@125]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertTrue(Assert.java:52)
at com.icnetbanking.testcases.TC_Register_003_Test.RegisterNewAccount(TC_Register_003_Test.java:57)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- RegisterNewAccount -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.icnetbanking.testcases.TC_Register_003_Test@57a3af25]" started-at="2023-05-11T20:02:42 AST" name="teardown" finished-at="2023-05-11T20:02:43 AST" duration-ms="259" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.icnetbanking.testcases.TC_Register_003_Test -->
      <class name="com.icnetbanking.testcases.TC_Login_002_Test">
        <test-method is-config="true" signature="setup(java.lang.reflect.Method)[pri:0, instance:com.icnetbanking.testcases.TC_Login_002_Test@7f3b84b8]" started-at="2023-05-11T20:01:53 AST" name="setup" finished-at="2023-05-11T20:01:55 AST" duration-ms="2581" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.icnetbanking.testcases.TC_Login_002_Test.InvalidCredentialsLogin(java.lang.String,java.lang.String,java.lang.String) throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="InvalidCredentialsLogin(java.lang.String,java.lang.String,java.lang.String)[pri:1, instance:com.icnetbanking.testcases.TC_Login_002_Test@7f3b84b8]" started-at="2023-05-11T20:01:55 AST" name="InvalidCredentialsLogin" data-provider="gettestdatafromexcel" finished-at="2023-05-11T20:02:00 AST" duration-ms="4337" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[poornima1982@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[selenium@1234]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Warning: No match for E-Mail Address and/or Password.]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- InvalidCredentialsLogin -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.icnetbanking.testcases.TC_Login_002_Test@7f3b84b8]" started-at="2023-05-11T20:02:00 AST" name="teardown" finished-at="2023-05-11T20:02:00 AST" duration-ms="421" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="setup(java.lang.reflect.Method)[pri:0, instance:com.icnetbanking.testcases.TC_Login_002_Test@7f3b84b8]" started-at="2023-05-11T20:02:00 AST" name="setup" finished-at="2023-05-11T20:02:03 AST" duration-ms="2967" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.icnetbanking.testcases.TC_Login_002_Test.InvalidCredentialsLogin(java.lang.String,java.lang.String,java.lang.String) throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="InvalidCredentialsLogin(java.lang.String,java.lang.String,java.lang.String)[pri:1, instance:com.icnetbanking.testcases.TC_Login_002_Test@7f3b84b8]" started-at="2023-05-11T20:02:03 AST" name="InvalidCredentialsLogin" data-provider="gettestdatafromexcel" finished-at="2023-05-11T20:02:10 AST" duration-ms="7367" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[swetha2010@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[selenium@123]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Warning: No match for E-Mail Address and/or Password.]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at com.icnetbanking.testcases.TC_Login_002_Test.InvalidCredentialsLogin(TC_Login_002_Test.java:47)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- InvalidCredentialsLogin -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.icnetbanking.testcases.TC_Login_002_Test@7f3b84b8]" started-at="2023-05-11T20:02:11 AST" name="teardown" finished-at="2023-05-11T20:02:11 AST" duration-ms="333" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="setup(java.lang.reflect.Method)[pri:0, instance:com.icnetbanking.testcases.TC_Login_002_Test@7f3b84b8]" started-at="2023-05-11T20:02:11 AST" name="setup" finished-at="2023-05-11T20:02:14 AST" duration-ms="2664" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.icnetbanking.testcases.TC_Login_002_Test.InvalidCredentialsLogin(java.lang.String,java.lang.String,java.lang.String) throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="InvalidCredentialsLogin(java.lang.String,java.lang.String,java.lang.String)[pri:1, instance:com.icnetbanking.testcases.TC_Login_002_Test@7f3b84b8]" started-at="2023-05-11T20:02:14 AST" name="InvalidCredentialsLogin" data-provider="gettestdatafromexcel" finished-at="2023-05-11T20:02:18 AST" duration-ms="4256" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[latha@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[pass@123]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Warning: No match for E-Mail Address and/or Password.]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at com.icnetbanking.testcases.TC_Login_002_Test.InvalidCredentialsLogin(TC_Login_002_Test.java:40)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- InvalidCredentialsLogin -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.icnetbanking.testcases.TC_Login_002_Test@7f3b84b8]" started-at="2023-05-11T20:02:18 AST" name="teardown" finished-at="2023-05-11T20:02:18 AST" duration-ms="337" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.icnetbanking.testcases.TC_Login_002_Test -->
      <class name="com.icnetbanking.testcases.TC_Login_001_Test">
        <test-method is-config="true" signature="setup(java.lang.reflect.Method)[pri:0, instance:com.icnetbanking.testcases.TC_Login_001_Test@4fb0f2b9]" started-at="2023-05-11T20:01:16 AST" name="setup" finished-at="2023-05-11T20:01:20 AST" duration-ms="3718" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.icnetbanking.testcases.TC_Login_001_Test.CheckValidUserPwdforLogin() throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="CheckValidUserPwdforLogin()[pri:1, instance:com.icnetbanking.testcases.TC_Login_001_Test@4fb0f2b9]" started-at="2023-05-11T20:01:20 AST" name="CheckValidUserPwdforLogin" finished-at="2023-05-11T20:01:25 AST" duration-ms="4845" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CheckValidUserPwdforLogin -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.icnetbanking.testcases.TC_Login_001_Test@4fb0f2b9]" started-at="2023-05-11T20:01:25 AST" name="teardown" finished-at="2023-05-11T20:01:25 AST" duration-ms="393" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="setup(java.lang.reflect.Method)[pri:0, instance:com.icnetbanking.testcases.TC_Login_001_Test@4fb0f2b9]" started-at="2023-05-11T20:01:25 AST" name="setup" finished-at="2023-05-11T20:01:28 AST" duration-ms="2993" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.icnetbanking.testcases.TC_Login_001_Test.CheckInValidUserPwdforLogin(java.lang.String,java.lang.String) throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="CheckInValidUserPwdforLogin(java.lang.String,java.lang.String)[pri:2, instance:com.icnetbanking.testcases.TC_Login_001_Test@4fb0f2b9]" started-at="2023-05-11T20:01:28 AST" name="CheckInValidUserPwdforLogin" data-provider="CustomdpNinjaLogin" finished-at="2023-05-11T20:01:36 AST" duration-ms="7192" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[swetha2010@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[selenium@123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at com.icnetbanking.testcases.TC_Login_001_Test.CheckInValidUserPwdforLogin(TC_Login_001_Test.java:94)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CheckInValidUserPwdforLogin -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.icnetbanking.testcases.TC_Login_001_Test@4fb0f2b9]" started-at="2023-05-11T20:01:36 AST" name="teardown" finished-at="2023-05-11T20:01:36 AST" duration-ms="252" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="setup(java.lang.reflect.Method)[pri:0, instance:com.icnetbanking.testcases.TC_Login_001_Test@4fb0f2b9]" started-at="2023-05-11T20:01:36 AST" name="setup" finished-at="2023-05-11T20:01:39 AST" duration-ms="2617" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.icnetbanking.testcases.TC_Login_001_Test.CheckInValidUserValidPwdforLogin(java.lang.String,java.lang.String) throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="CheckInValidUserValidPwdforLogin(java.lang.String,java.lang.String)[pri:3, instance:com.icnetbanking.testcases.TC_Login_001_Test@4fb0f2b9]" started-at="2023-05-11T20:01:39 AST" name="CheckInValidUserValidPwdforLogin" data-provider="CustomdpNinjaLogin" finished-at="2023-05-11T20:01:51 AST" duration-ms="11922" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[latha@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[selenium@123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at com.icnetbanking.testcases.TC_Login_001_Test.CheckInValidUserValidPwdforLogin(TC_Login_001_Test.java:123)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CheckInValidUserValidPwdforLogin -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.icnetbanking.testcases.TC_Login_001_Test@4fb0f2b9]" started-at="2023-05-11T20:01:51 AST" name="teardown" finished-at="2023-05-11T20:01:51 AST" duration-ms="455" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.icnetbanking.testcases.TC_Login_001_Test -->
    </test> <!-- BankingApp Test -->
  </suite> <!-- IcNetbanking -->
</testng-results>
